### Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "leo@gmail.com",
  "password": "123456"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "leo@gmail.com",
  "password": "123456"
}
